Remove crate-type
Breaks build with panic=abort:
> error: the linked panic runtime `panic_unwind` is not compiled with this crate's panic strategy `abort`